// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package ormmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          int64
	Method      string
	Header      []byte
	QueryParams []byte
	Body        []byte
	CreatedAt   pgtype.Timestamptz
	RoomID      pgtype.UUID
}
